services:
  app:
    build: .
    env_file: .env
    depends_on:
      - mongodb
      - redis
    networks:
      - ranking-network

  redis:
    image: redis/redis-stack:latest
    networks:
      - ranking-network

  mongodb:
    image: mongodb/mongodb-community-server:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongodb:/data/db
    networks:
      - ranking-network

networks:
  ranking-network:
    driver: bridge

volumes:
  mongodb:
